#!/bin/bash
set -e

echo config: Loading config
source build.config

TARGET=$1

read -r -p "All on $TARGET will be erased. Continue? [y/N] " response
response=${response,,}    # tolower
if ! [[ $response =~ ^(yes|y)$ ]]; then
        exit
fi

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

echo precheck: Checking preconditions before actual build
$DIR/precheck $FILESYSTEM

echo buildkernel: Building the kernel
if ! [ -d "build" ]; then
	mkdir build
	mkdir build/kernout
	cp kernel.config build/kernout/.config
fi
KERNOUT=$(realpath build/kernout)
KERNELSRC=$(realpath $KERNELSRC)
$DIR/buildkernel "$KERNOUT" "$KERNELSRC"

echo partition: Partitioning $TARGET
$DIR/partition $SWAPSIZE $TARGET $FILESYSTEM

echo Debootstrapping
$DIR/install $TARGET $UBUNTUVERSION $FILESYSTEM $BAUD $PACKAGES
