#!/bin/bash
set -e

SWAP="$1"1
TARGET="$1"2

echo "# Auto generated" > /etc/fstab
echo $SWAP swap swap defaults 0 0 >> /etc/fstab
echo $TARGET / $2 defaults 0 1  >> /etc/fstab

dpkg --install inst/linux-image*
apt-get -y install lilo
liloconfig

sed -i "s#^boot.\+#boot=$1#g" /etc/lilo.conf
sed -i "s#^install.\+#install = text#g" /etc/lilo.conf
sed -i "s#\#serial.\+#serial = 0,57600n8#g" /etc/lilo.conf
sed -i "s#\#append.\+#append = \"console=ttyS0,57600n8 reboot=bios\"#g" /etc/lilo.conf
sed -i "s#\"UUID=[^\"]\+\"#$TARGET#g" /etc/lilo.conf

lilo
exit
