#!/bin/bash
set -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

mkdir mnt
mount "$1"2 mnt
debootstrap --variant=minbase --arch=i386 $2 mnt http://de.archive.ubuntu.com/ubuntu
mkdir mnt/inst
mount --bind build mnt/inst
mount --bind /tmp mnt/tmp
mount --bind /dev mnt/dev
mount --bind /dev/pts mnt/dev/pts
mount -t sysfs /sys mnt/sys
mount -t proc /proc mnt/proc
cp /proc/mounts mnt/etc/mtab  
cp /etc/resolv.conf mnt/etc/resolv.conf 
echo "wrap" > mnt/etc/hostname

cp $DIR/chroot-install build
rm mnt/etc/init/tty?.conf
cp ttyS0.conf mnt/etc/init
cp eth0.conf mnt/etc/network/interfaces.d/eth0
cat modules >> mnt/etc/modules
chroot mnt inst/chroot-install $1 $3 $4 "$5" "$6"

umount mnt/proc
umount mnt/sys
umount mnt/dev/pts
umount mnt/dev
umount mnt/tmp
umount mnt/inst
rm -r mnt/inst

umount "$1"2
rm -r mnt
